pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/mohitkiloi/mohit-login-app.git'
            }
        }

        stage('Setup Python Env') {
            steps {
                bat 'python -m venv venv'
                bat '.\\venv\\Scripts\\pip install --upgrade pip'
                bat '.\\venv\\Scripts\\pip install -r requirements.txt'
            }
        }

        stage('Generate Fake Logs') {
            steps {
                bat '.\\venv\\Scripts\\python generate_fake_logs.py'
            }
        }

        stage('Train Isolation Forest') {
            steps {
                bat '.\\venv\\Scripts\\python train_model.py'
            }
        }

        stage('Detect Anomalies (Isolation Forest)') {
            steps {
                bat '.\\venv\\Scripts\\python detect_anomaly.py'
            }
        }

        stage('Build Graph (GNN)') {
            steps {
                bat '.\\venv\\Scripts\\python gnn\\graph_builder.py'
            }
        }

        stage('Train GNN Model') {
            steps {
                bat '.\\venv\\Scripts\\python gnn\\gnn_model.py'
            }
        }

        stage('Infer GNN') {
            steps {
                bat '.\\venv\\Scripts\\python gnn\\infer_gnn.py'
            }
        }

        stage('Archive Reports') {
            steps {
                archiveArtifacts artifacts: 'logs.csv, alert_report.csv, experiments/metrics_report.json, login_graph.csv, gnn_model.pth', fingerprint: true
            }
        }
    }
}
